### ISSUE TITLE
undefined method `environment' for nil:NilClass in rails-assets-bootstrap

### ISSUE THREAD

**Issue by OleMchls** [tenex/rails-assets#125]
During deployment to heroku I get the following error:

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       I, [2014-03-13T22:44:28.287603 #1023]  INFO -- : [librato-rails] starting up (pid 1023, using environment)...
       I, [2014-03-13T22:44:28.864898 #1023]  INFO -- : Writing /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/public/assets/deck-cover-placeholder-45fce7d5034f94b0bc317ef768cc6a29.png
       I, [2014-03-13T22:44:28.867287 #1023]  INFO -- : Writing /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/public/assets/deck-cover-placeholder-b696d0c639cc1ee28f83be54a8db2b5e.svg
       I, [2014-03-13T22:44:46.193097 #1023]  INFO -- : Writing /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/public/assets/application-a5fea314265e1536689240cfd17fd626.js
       rake aborted!
       undefined method `environment' for nil:NilClass
       (in /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/rails-assets-bootstrap-3.1.1/vendor/assets/stylesheets/bootstrap.scss)
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-rails-4.0.1/lib/sass/rails/importer.rb:84:in `evaluate'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-rails-4.0.1/lib/sass/rails/importer.rb:70:in `engine_from_path'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-rails-4.0.1/lib/sass/rails/importer.rb:27:in `find_relative'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/import_node.rb:48:in `import'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/import_node.rb:28:in `imported_file'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/import_node.rb:37:in `css_import?'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:283:in `visit_import'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/base.rb:36:in `visit'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:152:in `block in visit'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/stack.rb:79:in `block in with_base'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/stack.rb:121:in `with_frame'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/stack.rb:79:in `with_base'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:152:in `visit'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/base.rb:52:in `map'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/base.rb:52:in `visit_children'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:161:in `block in visit_children'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:173:in `with_environment'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:160:in `visit_children'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/base.rb:36:in `block in visit'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:180:in `visit_root'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/base.rb:36:in `visit'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:151:in `visit'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/visitors/perform.rb:8:in `visit'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/root_node.rb:36:in `css_tree'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/tree/root_node.rb:20:in `render'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sass-3.3.2/lib/sass/engine.rb:274:in `render'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/sass_template.rb:53:in `evaluate'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/context.rb:197:in `block in evaluate'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/context.rb:194:in `each'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/context.rb:194:in `evaluate'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/processed_asset.rb:12:in `initialize'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:374:in `new'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:374:in `block in build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:395:in `circular_call_protection'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:373:in `build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:61:in `find_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/processed_asset.rb:105:in `each'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/processed_asset.rb:16:in `initialize'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:374:in `new'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:374:in `block in build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:395:in `circular_call_protection'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:373:in `build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:61:in `find_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/bundled_asset.rb:16:in `initialize'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:377:in `new'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:377:in `build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/index.rb:61:in `find_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/manifest.rb:257:in `benchmark'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/manifest.rb:210:in `find_asset'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/manifest.rb:119:in `block in compile'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/manifest.rb:118:in `each'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/sprockets/manifest.rb:118:in `compile'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:60:in `block (3 levels) in define'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-2.12.0/lib/rake/sprocketstask.rb:146:in `with_logger'
       /tmp/build_35dfd207-8599-4196-99e7-64ee425380f7/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:59:in `block (2 levels) in define'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !

 !     Push rejected, failed to compile Multipack app
```

This is my `Gemfile.lock`

```
GEM
  remote: https://rubygems.org/
  remote: https://rails-assets.org/
  specs:
    actionmailer (4.0.3)
      actionpack (= 4.0.3)
      mail (~> 2.5.4)
    actionpack (4.0.3)
      activesupport (= 4.0.3)
      builder (~> 3.1.0)
      erubis (~> 2.7.0)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    activemodel (4.0.3)
      activesupport (= 4.0.3)
      builder (~> 3.1.0)
    activerecord (4.0.3)
      activemodel (= 4.0.3)
      activerecord-deprecated_finders (~> 1.0.2)
      activesupport (= 4.0.3)
      arel (~> 4.0.0)
    activerecord-deprecated_finders (1.0.3)
    activesupport (4.0.3)
      i18n (~> 0.6, >= 0.6.4)
      minitest (~> 4.2)
      multi_json (~> 1.3)
      thread_safe (~> 0.1)
      tzinfo (~> 0.3.37)
    aggregate (0.2.2)
    arel (4.0.2)
    atomic (1.1.15)
    bcrypt (3.1.7)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    better_errors (1.1.0)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.1.4)
    capybara (2.2.1)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    celluloid (0.15.2)
      timers (~> 1.1.0)
    cliver (0.3.2)
    coderay (1.1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-rails-source-maps (1.4.0)
      coffee-script-source (>= 1.6.1)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.7.0)
    columnize (0.3.6)
    connection_pool (1.2.0)
    cucumber (1.3.11)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.12)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.0.2)
    cucumber-rails (1.4.0)
      capybara (>= 1.1.2)
      cucumber (>= 1.2.0)
      nokogiri (>= 1.5.0)
      rails (>= 3.0.0)
    database_cleaner (1.2.0)
    debug_inspector (0.0.2)
    debugger (1.6.6)
      columnize (>= 0.3.1)
      debugger-linecache (~> 1.2.0)
      debugger-ruby_core_source (~> 1.3.2)
    debugger-linecache (1.2.0)
    debugger-ruby_core_source (1.3.2)
    devise (3.2.3)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.2.5)
    docsplit (0.7.4)
    dotenv (0.10.0)
    dotenv-rails (0.10.0)
      dotenv (= 0.10.0)
    erubis (2.7.0)
    excon (0.31.0)
    execjs (2.0.2)
    fakes3 (0.1.5.2)
      builder
      thor
    faraday (0.9.0)
      multipart-post (>= 1.2, < 3)
    fog (1.20.0)
      builder
      excon (~> 0.31.0)
      formatador (~> 0.2.0)
      mime-types
      multi_json (~> 1.0)
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
      nokogiri (>= 1.5.11)
    foreman (0.63.0)
      dotenv (>= 0.7)
      thor (>= 0.13.6)
    formatador (0.2.4)
    gherkin (2.12.2)
      multi_json (~> 1.3)
    haml (4.0.5)
      tilt
    hashie (2.0.5)
    hike (1.2.3)
    i18n (0.6.9)
    jbuilder (1.5.3)
      activesupport (>= 3.0.0)
      multi_json (>= 1.2.0)
    jquery-fileupload-rails (0.4.1)
      actionpack (>= 3.1)
      railties (>= 3.1)
    jquery-rails (3.1.0)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.1)
    jwt (0.1.11)
      multi_json (>= 1.5)
    kgio (2.9.2)
    librato-metrics (1.3.0)
      aggregate (~> 0.2.2)
      faraday (~> 0.7)
      multi_json
    librato-rack (0.4.4)
      librato-metrics (~> 1.1)
    librato-rails (0.10.2)
      librato-rack (~> 0.4.2)
      rails (>= 3.0)
    librato-sidekiq (0.1.2)
      sidekiq
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    method_source (0.8.2)
    mime-types (1.25.1)
    mini_portile (0.5.2)
    minitest (4.7.5)
    multi_json (1.9.0)
    multi_test (0.0.3)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.8.0)
    nokogiri (1.6.1)
      mini_portile (~> 0.5.0)
    oauth2 (0.9.3)
      faraday (>= 0.8, < 0.10)
      jwt (~> 0.1.8)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    omniauth (1.2.1)
      hashie (>= 1.2, < 3)
      rack (~> 1.0)
    omniauth-github (1.1.1)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.1)
    omniauth-oauth2 (1.1.2)
      faraday (>= 0.8, < 0.10)
      multi_json (~> 1.3)
      oauth2 (~> 0.9.3)
      omniauth (~> 1.2)
    orm_adapter (0.5.0)
    pg (0.17.1)
    poltergeist (1.5.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    polyglot (0.3.4)
    pry (0.9.12.6)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    pry-rails (0.3.2)
      pry (>= 0.9.10)
    rack (1.5.2)
    rack-protection (1.5.2)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.0.3)
      actionmailer (= 4.0.3)
      actionpack (= 4.0.3)
      activerecord (= 4.0.3)
      activesupport (= 4.0.3)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.3)
      sprockets-rails (~> 2.0.0)
    rails-assets-angular (1.2.14)
    rails-assets-angular-touch (1.2.14)
      rails-assets-angular (= 1.2.14)
    rails-assets-bootstrap (3.1.1)
      rails-assets-jquery (>= 1.9.0)
    rails-assets-components-font-awesome (4.0.3)
    rails-assets-jquery (2.1.0)
    rails-assets-mousetrap (1.4.6)
    rails-assets-ngprogress (1.0.4)
    rails_12factor (0.0.2)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.2)
    rails_stdout_logging (0.0.3)
    railties (4.0.3)
      actionpack (= 4.0.3)
      activesupport (= 4.0.3)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.13.0)
    rake (10.1.1)
    rdoc (4.1.1)
      json (~> 1.4)
    redcarpet (3.1.1)
    redis (3.0.7)
    redis-namespace (1.4.1)
      redis (~> 3.0.4)
    s3_direct_upload (0.1.7)
      coffee-rails (>= 3.1)
      jquery-fileupload-rails (~> 0.4.1)
      rails (>= 3.1)
      sass-rails (>= 3.1)
    sass (3.3.2)
    sass-rails (4.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (>= 3.1.10)
      sprockets-rails (~> 2.0.0)
    sdoc (0.4.0)
      json (~> 1.8)
      rdoc (~> 4.0, < 5.0)
    sidekiq (2.17.7)
      celluloid (>= 0.15.2)
      connection_pool (>= 1.0.0)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sinatra (1.4.4)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    slop (3.5.0)
    sprockets (2.12.0)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.0.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (~> 2.8)
    thor (0.18.1)
    thread_safe (0.2.0)
      atomic (>= 1.1.7, < 2)
    tilt (1.4.1)
    timers (1.1.0)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    turbolinks (2.2.1)
      coffee-rails
    tzinfo (0.3.39)
    uglifier (2.4.0)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.3)
      unf_ext
    unf_ext (0.0.6)
    unicorn (4.8.2)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    warden (1.2.3)
      rack (>= 1.0)
    websocket-driver (0.3.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  better_errors
  binding_of_caller
  coffee-rails (~> 4.0.0)
  coffee-rails-source-maps
  cucumber-rails
  database_cleaner
  debugger (~> 1.6.5)
  devise
  docsplit
  dotenv-rails
  fakes3
  fog
  foreman
  haml
  jbuilder (~> 1.2)
  jquery-rails
  librato-rails
  librato-sidekiq
  omniauth
  omniauth-github
  pg
  poltergeist
  pry-rails
  rails (~> 4.0.0)
  rails-assets-angular
  rails-assets-angular-touch
  rails-assets-bootstrap
  rails-assets-components-font-awesome
  rails-assets-mousetrap
  rails-assets-ngprogress
  rails_12factor
  redcarpet
  s3_direct_upload
  sass-rails (~> 4.0.0)
  sdoc
  sidekiq
  sinatra (>= 1.3.0)
  turbolinks
  uglifier (>= 1.3.0)
  unf
  unicorn
```

I assume it's not a rails-assets problem. But as requested on [twitter](https://twitter.com/CodeStars/status/444242946595233792) I will post this here

**Comment by sheerun** [comment]
Did you try https://devcenter.heroku.com/articles/labs-user-env-compile ?

**Comment by OleMchls** [comment]
Not yet, I'll give it a try

**Comment by OleMchls** [comment]
Just enabled but still the same error :pensive:

**Comment by sheerun** [comment]
@nesQuick Downgrade sass-rails to 2.11.0: https://github.com/rails/sass-rails/issues/191

**Comment by OleMchls** [comment]
Jup, thank you for the help. But its locking sprockets to 2.11.0 as you see here: https://github.com/rails/sass-rails/issues/191#issuecomment-37596464

``` ruby
gem 'sprockets', '~> 2.8', '<= 2.11.0'
```

**Comment by sheerun** [comment]
4.0.2 was released 2 minutes ago :P

**Comment by OleMchls** [comment]
haha :D No shit. Ok I just removed my lock.
Again, thanks for the quick help :+1: Maybe we should all do a deps free language :dancer:

**Comment by sheerun** [comment]
no problem :) btw. I suggest using https://github.com/sheerun/s3_file_field instead of s3_direct_upload. It supports multiple inputs per form, and is easier to setup.
