### ISSUE TITLE
RailsAssets is  not a class (TypeError)

### ISSUE THREAD

**Issue by mcfiredrill** [tenex/rails-assets#188]
Getting this error after I tried to install rails-assets-jquery-payment. I'm using several rails assets successfully in this project already. Maybe there is some jquery conflict going on?

```
$ rails s
/Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rails-assets-jquery.payment-1.1.4/lib/rails-assets-jquery.payment.rb:35:in `<top (required)>': RailsAssets is 
not a class (TypeError)
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
        from /Users/tony/src/streamify/config/application.rb:7:in `<top (required)>'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.2.rc1/lib/rails/commands/commands_tasks.rb:79:in `require'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.2.rc1/lib/rails/commands/commands_tasks.rb:79:in `block in server'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.2.rc1/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.2.rc1/lib/rails/commands/commands_tasks.rb:76:in `server'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.2.rc1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.2.rc1/lib/rails/commands.rb:17:in `<top (required)>'
        from /Users/tony/src/streamify/bin/rails:8:in `require'
        from /Users/tony/src/streamify/bin/rails:8:in `<top (required)>'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in `load'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in `call'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/client/command.rb:7:in `call'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/client.rb:26:in `run'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/bin/spring:48:in `<top (required)>'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/binstub.rb:11:in `load'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/binstub.rb:11:in `<top (required)>'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/tony/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/tony/src/streamify/bin/spring:16:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

**Comment by sheerun** [comment]
Please try to reinstall all your gems: `gem list | grep rails-assets | cut -d ' ' -f 1 | xargs gem uninstall -aI`.

It's probably conflict between gem version before and after our big update :(

**Comment by mcfiredrill** [comment]
Thanks.

Hmm now I seem to be getting the error from the rest of my rails-assets gems. I'm on 0.5.2 of the rails-assets gem.

**Comment by sheerun** [comment]
Could you send your Gemfile?

**Comment by mcfiredrill** [comment]
```
source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '4.1.2.rc1'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'

gem 'spring',        group: :development

gem 'devise'
gem 'cancancan'
gem 'stripe'
gem 'docker-api', require: 'docker'
gem 'simple_form'

gem 'sidekiq'
gem 'therubyracer'
gem 'less-rails'
gem 'twitter-bootstrap-rails', '~> 3.2.0'
gem 'font-awesome-sass', '~> 4.2.0'
gem 'rails-assets'
gem 'rails-assets-countUp.js'
gem 'rails-assets-nvd3'
gem 'rails-assets-moment'
gem 'rails-assets-fullcalendar'
gem 'rails-assets-jquery.payment'

gem 'rspec-rails', :group => [:development, :test]

gem 'dotenv-rails'
gem 'unicorn'


gem 'capistrano', '~> 3.2.1'
gem 'capistrano-rails', '~> 1.1.2'
gem 'capistrano-bundler'
gem 'capistrano-rbenv', "~>2.0"
```

**Comment by mcfiredrill** [comment]
I removed all of rails assets gems from my Gemfile except rails-assets itself, so I could run rails c with pry. I used `$ RailsAssets -a` and got these files back:

```
Found 2 candidates for `RailsAssets` definition:

Candidate 1/2: /Users/tony/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rails-assets-0.5.2/lib/frontend-helpers/analytics_helper.rb @ line 1:
Number of lines: 39

module RailsAssets
  module AnalyticsHelper

    def analytics(options = [])
      options.each do |s|
        send(s.to_s)
      end
    end

    def google
      if !(ENV['GOOGLE_ACCOUNT_ID']).blank? && !(ENV['GOOGLE_SITE_NAME']).blank?
        haml_tag :script do
          haml_concat "var _gaq = _gaq || []; _gaq.push(['_setAccount', '#{ENV['GOOGLE_ACCOUNT_ID']}']); _gaq.push(['_setDomainName', '#{ENV['GOOGLE_SITE_NAME']}']); _gaq.push(['_trackPageview']);(function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();"
        end
      end
    end

    def mixpanel
      if !(ENV['MIXPANEL_INIT']).blank?
        haml_tag :script do
          haml_concat "(function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement('script');b.type='text/javascript';b.async=!0;b.src=('https:'===c.location.protocol?'https:':'http:')+'//cdn.mxpnl.com/libs/mixpanel-2.1.min.js';d=c.getElementsByTagName('script')[0];d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){var c=b.split('.');2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(Array.prototype.slice.call(arguments,0)))}}var g=a;'undefined'!==typeof f?"
          haml_concat "g=a[f]=[]:f='mixpanel';g.people=g.people||[];h='disable track track_pageview track_links track_forms register register_once unregister identify name_tag set_config people.identify people.set people.increment'.split(' ');for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.1})(document,window.mixpanel||[]);"
          haml_concat "mixpanel.init('#{ENV['MIXPANEL_INIT']}');"
        end
      end
    end

    def woopra
      if !(ENV['WOOPRA_DOMAIN']).blank?
        haml_tag :script do
                  haml_concat "function woopraReady(tracker) {tracker.setDomain('#{ENV['WOOPRA_DOMAIN']}');tracker.setIdleTimeout(300000);tracker.trackPageview({type:'pageview',url:window.location.pathname+window.location.search,title:document.title});return false;}"
                  haml_concat "(function() {var wsc = document.createElement('script');wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';wsc.type = 'text/javascript';wsc.async = true;var ssc = document.getElementsByTagName('script')[0];ssc.parentNode.insertBefore(wsc, ssc);})();"
        end
      end
    end


  end
end

Candidate 2/2: /Users/tony/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rails-assets-0.5.2/lib/frontend-helpers/meta_helper.rb @ line 1:
Number of lines: 45

module RailsAssets
  module MetaHelper
    # --------------------------------------------------------------------------          
```

I can't seem to locate these files with git log:

```
🍒tony@moguya ~/src/rails-assets(master)$ git log -- lib/frontend-helpers/analytics_helper.rb
🍒tony@moguya ~/src/rails-assets(master)$ git log -- lib/frontend-helpers/meta_helper.rb
```

**Comment by mcfiredrill** [comment]
Wait, the `rails-assets` gem is a totally different thing?

https://rubygems.org/gems/rails-assets

**Comment by sheerun** [comment]
You don't need to use `rails-assets` gem. It's not even ours.

**Comment by mcfiredrill** [comment]
Ah I see that now, sorry I got confused!

**Comment by mcfiredrill** [comment]
Homepage for that gem doesn't exist anymore, who knows what it even is?

Times like this you really wish rubygems.org had some sort of policy for abandoned gems. :sob:
