### ISSUE TITLE
ocLazyLoad package fails to build.

### ISSUE THREAD

**Issue by phyllisstein** [tenex/rails-assets#202]
Hey there! Just wanted to give you a heads-up that ocombe/ocLazyLoad is failing to update in Rails Assets. The last version to be gemified was 0.3.8, and when I tried to update it I got the following exception:

```
ocLazyLoad#0.5.1: rake aborted!
There was a Gem::Requirement::BadRequirementError while loading rails-assets-ocLazyLoad.gemspec: 
Illformed requirement ["."] from
  /tmp/d20141218-10513-1lqw9bs/rails-assets-ocLazyLoad.gemspec:18:in `block in <main>'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler.rb:394:in `rescue in eval_gemspec'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler.rb:383:in `eval_gemspec'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler.rb:354:in `block in load_gemspec_uncached'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/shared_helpers.rb:52:in `chdir'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/shared_helpers.rb:52:in `chdir'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler.rb:349:in `load_gemspec_uncached'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler.rb:339:in `load_gemspec'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/gem_helper.rb:31:in `initialize'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/gem_helper.rb:13:in `new'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/gem_helper.rb:13:in `install_tasks'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/gem_tasks.rb:2:in `<top (required)>'
/tmp/d20141218-10513-1lqw9bs/Rakefile:1:in `require'
/tmp/d20141218-10513-1lqw9bs/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
```

Not quite sure what's up, but the developer said he's happy to fix any issues if you help to pin the trouble down. Thanks in advance for your help---and for building a _completely_ invaluable project.

**Comment by sheerun** [comment]
fixed by 585d09d58d9c48adc3cb0bb3e594fe6614c12a6b
