### ISSUE TITLE
Exception on build latest marionette assets( Rubygems does not support || in version string '^1.8.0 || ^2.0.0' )

### ISSUE THREAD

**Issue by tamadamas** [tenex/rails-assets#203]
I checked it happens in jquery lib, because that version is on the website http://marionettejs.com/
I installed it with `bower install` manually and It was `2.1.3` version.
What if It will be as next expression instead exception?

```
if version.include?('||')
   version = 'latest'    
end
```

```
bin/rake 'component:convert[marionette,2.3.0]'                                                                                                           maxim@matrix
I, [2014-12-21T15:13:47.563571 #28371]  INFO -- : ** [Raven] Raven 0.6.0 ready to catch errors
[fyi] /home/maxim/dev/rails-assets/node_modules/.bin/bower install -p -F marionette#2.3.0 --json --config.tmp=/tmp/bower20141221-28371-14jjs6r/tmp --config.storage.packages=/tmp/bower20141221-28371-14jjs6r/cache --config.interactive=false
rake aborted!
Rubygems does not support || in version string '^1.8.0 || ^2.0.0'
/home/maxim/dev/rails-assets/app/models/build/utils.rb:61:in `fix_version_string'
/home/maxim/dev/rails-assets/app/models/build/utils.rb:172:in `block in fix_dependencies'
/home/maxim/dev/rails-assets/app/models/build/utils.rb:169:in `each'
/home/maxim/dev/rails-assets/app/models/build/utils.rb:169:in `map'
/home/maxim/dev/rails-assets/app/models/build/utils.rb:169:in `fix_dependencies'
```

Hm, I've found `rails-assets-marionette-gem` latest version. But It's a mess with this one: 3 rails-assets  gem to one bower lib

**Comment by sheerun** [comment]
I agree. It's better than completely blocking build..
