### ISSUE TITLE
Dependencies of Dependncies are not included

### ISSUE THREAD

**Issue by pencilcheck** [tenex/rails-assets#231]
Sample Gemfile:

```
gem 'rails-assets-angular-masonry'
```

```
    rails-assets-angular-masonry (0.11.0)
      rails-assets-angular (~> 1.3.0)
      rails-assets-imagesloaded (~> 3.1.0)
      rails-assets-jquery (~> 2.1.0)
      rails-assets-masonry (~> 3.2.0)

    rails-assets-masonry (3.2.1)
      rails-assets-get-size (>= 1.1.4, < 1.3)
      rails-assets-outlayer (~> 1.3.0)
```

When running deploying the application:

```
       rake aborted!
       LoadError: cannot load such file -- rails-assets-desandro--get-size
       /var/www/wwm/tmp/build-142456279313211/vendor/bundle/ruby/2.1.0/gems/rails-assets-outlayer-1.3.0/lib/rails-assets-outlayer.rb:6:in `require'
       /var/www/wwm/tmp/build-142456279313211/vendor/bundle/ruby/2.1.0/gems/rails-assets-outlayer-1.3.0/lib/rails-assets-outlayer.rb:6:in `<top (required)>'
       /var/www/wwm/tmp/build-142456279313211/vendor/bundle/ruby/2.1.0/gems/rails-assets-masonry-3.2.1/lib/rails-assets-masonry.rb:4:in `require'
       /var/www/wwm/tmp/build-142456279313211/vendor/bundle/ruby/2.1.0/gems/rails-assets-masonry-3.2.1/lib/rails-assets-masonry.rb:4:in `<top (required)>'
       /var/www/wwm/tmp/build-142456279313211/vendor/bundle/ruby/
```

Seems like rails-assets-outlayer has a dependency of rails-assets-desandro--get-size, however the dependencies of that is not automatically loaded, so it cannot load such file.

The problem goes away if I include the dependency manually like so

```
  gem 'rails-assets-desandro--get-size'
```

**Comment by sheerun** [comment]
Works for me. Maybe try to uninstall all production rails-assets gems.

**Comment by pencilcheck** [comment]
What do you mean by uninstall?

**Comment by sheerun** [comment]
Something like `rails-assets-angular-masonry`, so they are removed from rubygems cache.

**Comment by sheerun** [comment]
Something like `gem uninstall rails-assets-angular-masonry`, so they are removed from rubygems cache.

**Comment by pencilcheck** [comment]
Ok, I will try that.

**Comment by pencilcheck** [comment]
I think it has fixed itself. Closing.
