### ISSUE TITLE
trackingjs isn't building

### ISSUE THREAD

**Issue by hadees** [tenex/rails-assets#313]
For some reason [trackingjs](https://github.com/eduardolundgren/tracking.js) isn't building

```
rake aborted!
Bundler::GemspecError: There was a Gem::Requirement::BadRequirementError while loading rails-assets-tracking.gemspec: 
Illformed requirement ["r67"] from
  /tmp/d20160304-30808-1tjt7o7/rails-assets-tracking.gemspec:19:in `block in <main>'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:394:in `rescue in eval_gemspec'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:383:in `eval_gemspec'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:344:in `block in load_gemspec_uncached'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `chdir'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:52:in `chdir'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:339:in `load_gemspec_uncached'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:329:in `load_gemspec'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:31:in `initialize'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:13:in `new'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:13:in `install_tasks'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/gem_tasks.rb:5:in `<top (required)>'
/tmp/d20160304-30808-1tjt7o7/Rakefile:1:in `require'
/tmp/d20160304-30808-1tjt7o7/Rakefile:1:in `<top (required)>'
Gem::Requirement::BadRequirementError: Illformed requirement ["r67"]
/tmp/d20160304-30808-1tjt7o7/rails-assets-tracking.gemspec:19:in `block in <main>'
/tmp/d20160304-30808-1tjt7o7/rails-assets-tracking.gemspec:6:in `new'
/tmp/d20160304-30808-1tjt7o7/rails-assets-tracking.gemspec:6:in `<main>'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:383:in `eval'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:383:in `eval_gemspec'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:344:in `block in load_gemspec_uncached'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `chdir'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:52:in `chdir'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:339:in `load_gemspec_uncached'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:329:in `load_gemspec'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:31:in `initialize'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:13:in `new'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:13:in `install_tasks'
/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/gem_tasks.rb:5:in `<top (required)>'
/tmp/d20160304-30808-1tjt7o7/Rakefile:1:in `require'
/tmp/d20160304-30808-1tjt7o7/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by hut8** [comment]
That's because the bower.json file in the repository isn't valid:

https://github.com/eduardolundgren/tracking.js/blob/master/bower.json#L20

If the r67 is a tag or something, you can specify that in a URL. For details, see https://github.com/bower/spec/blob/master/json.md#dependencies

**Comment by hut8** [comment]
Closing due to silence for > 30 days.
