### ISSUE TITLE
Unable to access rails-assets.org

### ISSUE THREAD

**Issue by snowdall** [tenex/rails-assets#330]
When using jruby and a Gemfile that uses a block to access rails-assets.org there is a certificate failure when doing a bundle install.  Originally I fixed this by going from https to http on the block.  But it seems that within the last week or so your hosting redirected the insecure access over to the secure access.  I have tried multiple means to resolve this issue but have not been able to.  It appears to be a problem with how the JVM handles the certificates as opposed to Ruby.  If you know of a simple solution, or could take the redirect off that would be great.  I have already spent way too much time dealing with this and actually need to get to working on what I'm supposed to be working on.  Here's the stack trace.

```
#<Gem::RemoteFetcher::FetchError: certificate verify failed (https://rails-assets.org/specs.4.8.gz)>
/Users/csnowdal/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/request.rb:94:in `connection_for'
/Users/csnowdal/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/request.rb:146:in `perform_request'
/Users/csnowdal/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/request.rb:115:in `fetch'
/Users/csnowdal/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/remote_fetcher.rb:378:in `request'
/Users/csnowdal/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/remote_fetcher.rb:251:in `fetch_http'
/Users/csnowdal/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/remote_fetcher.rb:289:in `fetch_path'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:520:in `fetch_specs'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:537:in `fetch_all_remote_specs'
/Users/csnowdal/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/source_list.rb:91:in `each'
org/jruby/RubyArray.java:1613:in `each'
/Users/csnowdal/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/source_list.rb:91:in `each'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:535:in `fetch_all_remote_specs'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/fetcher.rb:382:in `fetch_all_remote_specs'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/fetcher.rb:197:in `specs'
org/jruby/RubyProc.java:271:in `call'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/retry.rb:38:in `run'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/retry.rb:28:in `attempt'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/fetcher.rb:196:in `specs'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:311:in `remote_specs'
org/jruby/RubyArray.java:1613:in `each'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:309:in `remote_specs'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/index.rb:9:in `build'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:305:in `remote_specs'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:79:in `specs'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/definition.rb:204:in `index'
org/jruby/RubyArray.java:1613:in `each'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/definition.rb:202:in `index'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/index.rb:9:in `build'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/definition.rb:199:in `index'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/definition.rb:193:in `resolve'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/definition.rb:132:in `specs'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/definition.rb:121:in `resolve_remotely!'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/installer.rb:79:in `run'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/installer.rb:18:in `install'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/cli/install.rb:80:in `run'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/cli.rb:157:in `install'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/cli.rb:10:in `start'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/bin/bundle:20:in `(root)'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/gems/bundler-1.9.4/bin/bundle:18:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
/Users/csnowdal/.rvm/gems/jruby-1.7.19@helios/bin/bundle:23:in `(root)'
```

**Comment by hut8** [comment]
There are a couple of issues with SSL that users have had. We actually haven't changed the redirect recently; the last time that was changed was actually when we took over hosting which was in March. That stack trace doesn't actually include the exception. I'm working on reproducing it with our new SSL setup, and I'm also adding an `http://insecure.rails-assets.org` endpoint.

**Comment by hut8** [comment]
I updated the comment; I'm working on reproducing it and also adding an insecure endpoint due to multiple users with either Windows or JRuby (or both) having issues with their certificates.

**Comment by hut8** [comment]
Recently we added a new endpoint that might make things easier for managing certificates that we intend only to be used in development. You can use `http://insecure.rails-assets.org` and it won't redirect you to `https://`. Hope this helps :+1:
