### ISSUE TITLE
SSL verify failing on rails-assets.org - certificate is not yet valid

### ISSUE THREAD

**Issue by sbeam** [tenex/rails-assets#377]
Have been bundling with rails-assets.org in a docker container for weeks, but today - using the latest ubuntu image and ruby 2.3.1 with openssl 1.1.0 - bundler started raising `Bundler::Fetcher::CertificateFailureError`.

Put a simple test Dockerfile together like this:

```
 FROM ubuntu

 RUN apt-get update && apt-get install -qq -y openssl ruby --fix-missing --no-install-recommends

 RUN apt-get install ca-certificates
 RUN ruby -r openssl -e 'puts RUBY_VERSION; puts OpenSSL::VERSION; puts OpenSSL::OPENSSL_VERSION'
 RUN ruby -e 'require "net/http"; require "uri"; Net::HTTP.get(URI("https://rails-assets.org"))'
```

the result: 

```
 $ docker build .
 Sending build context to Docker daemon 14.85 kB
 Step 1 : FROM ubuntu
  ---> bd3d4369aebc
 Step 2 : RUN apt-get update && apt-get install -qq -y openssl ruby --fix-missing --no-install-recommends
  ---> Using cache
  ---> 02d41a32a0c6
 Step 3 : RUN apt-get install ca-certificates
  ---> Using cache
  ---> 3380f2274718
 Step 4 : RUN ruby -r openssl -e 'puts RUBY_VERSION; puts OpenSSL::VERSION; puts OpenSSL::OPENSSL_VERSION'
  ---> Using cache
  ---> 9ac3779a63f2
 Step 5 : RUN ruby -e 'require "net/http"; require "uri"; Net::HTTP.get(URI("https://rails-assets.org"))'
  ---> Running in 4763be95a506
 /usr/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
         from /usr/lib/ruby/2.3.0/net/http.rb:933:in `connect'
         from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
         from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
         from /usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
         from /usr/lib/ruby/2.3.0/net/http.rb:479:in `get_response'
         from /usr/lib/ruby/2.3.0/net/http.rb:456:in `get'
         from -e:1:in `<main>'
```

adding a `openssl s_client -connect rails-assets.org:443` command results in

```
...
subject=/CN=rails-assets.org
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits

---
SSL handshake has read 3489 bytes and written 431 bytes

---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: xxxx
    Session-ID-ctx:
    Master-Key: xxxx
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1473333735
    Timeout   : 300 (sec)
    Verify return code: 9 (certificate is not yet valid)
```

I assume this would be the same under a fresh linux install.

**Comment by hut8** [comment]
Start time of session is 1473333735, which is... Thu, 08 Sep 2016 11:22:15 GMT. Today's the 12th. The newest certificate was issued like two days ago, so that would cause this. Is your clock wrong?

**Comment by sbeam** [comment]
yep, apparently I was a victim of docker for mac clock drift. restarting docker fixes this issue. thanks, sorry for noise 😳

**Comment by hut8** [comment]
No problem at all! Glad I could be of some assistance.
