### ISSUE TITLE
404 when accessing ruby-assets.org/versions

### ISSUE THREAD

**Issue by ss44** [tenex/rails-assets#388]
bundler failing when trying to run install due to https://rails-assets.org/versions returning 404. 

Running bundle install triggers the following error:

```
Found no changes, using resolution from the lockfile
HTTP GET https://rails-assets.org/versions
HTTP 404 Not Found https://rails-assets.org/versions
Bundler::Fetcher::FallbackError: Net::HTTPNotFound
/usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/fetcher/downloader.rb:34:in `fetch'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:115:in `call'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:42:in `block in update'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
  /usr/local/rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
```

**Comment by hut8** [comment]
Did bundler just remove support for the old index format? If so, we're in trouble.

Related: https://github.com/tenex/rails-assets/issues/332

**Comment by ss44** [comment]
Just got word that this may have been related to a memory error on one our systems which was leading to this use case to being triggered.
