### ISSUE TITLE
Could not find rails-assets-jquery-3.4.1.gem for installation

### ISSUE THREAD

**Issue by rgaufman** [tenex/rails-assets#476]
When I try to run bundle, I see:

```
iMac.local ➜  timeagent git:(master) bundle --verbose
Running `bundle install --verbose` with bundler 2.2.27
Found no changes, using resolution from the lockfile
...
Updating files in vendor/cache
Could not find rails-assets-jquery-3.4.1.gem for installation
Bundler::GemNotFound: Could not find rails-assets-jquery-3.4.1.gem for installation
/usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:357:in `cached_gem'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/source/rubygems.rb:239:in `cache'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:129:in `block in cache'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/spec_set.rb:136:in `each'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/spec_set.rb:136:in `each'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:125:in `cache'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli/install.rb:63:in `block in run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli/install.rb:62:in `run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:252:in `block in install'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/settings.rb:131:in `temporary'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:251:in `install'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:31:in `dispatch'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:25:in `start'
  /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/exe/bundle:49:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/exe/bundle:37:in `<top (required)>'
  /usr/local/opt/ruby@2.7/bin/bundle:23:in `load'
  /usr/local/opt/ruby@2.7/bin/bundle:23:in `<main>'
```

Any ideas? - I am not sure if this is related to doing a brew upgrade recently, but not sure what to do to troubleshoot.

**Comment by hut8** [comment]
Sorry for delay. Is this still an issue?

**Comment by hut8** [comment]
Feel free to reopen if it is still an issue.
