### ISSUE TITLE
Error when trying to install jquery-ujs

### ISSUE THREAD

**Issue by brennovich** [tenex/rails-assets#72]
Putting `gem 'rails-assets-jquery-ujs'` breaks bundler:

```
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rails-assets.org/.
Fetching source index from https://rails-assets.org/
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/rubygems.rb:517:in `inflate': incorrect header check (Zlib::DataError)
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/rubygems.rb:517:in `inflate'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/fetcher.rb:93:in `fetch_spec'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/remote_specification.rb:46:in `_remote_specification'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/remote_specification.rb:51:in `method_missing'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/index.rb:95:in `block (2 levels) in unmet_dependency_names'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/index.rb:94:in `map'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/index.rb:94:in `block in unmet_dependency_names'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/index.rb:93:in `map'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/index.rb:93:in `unmet_dependency_names'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:240:in `remote_specs'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:163:in `fetch_specs'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:67:in `specs'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:192:in `block (2 levels) in index'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:189:in `each'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:189:in `block in index'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/index.rb:9:in `build'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:185:in `index'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:179:in `resolve'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:109:in `resolve_remotely!'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/installer.rb:83:in `run'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/installer.rb:14:in `install'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/cli.rb:247:in `install'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/vendor/thor/task.rb:27:in `run'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/vendor/thor.rb:344:in `dispatch'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/vendor/thor/base.rb:434:in `start'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/bin/bundle:20:in `block in <top (required)>'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/friendly_errors.rb:3:in `with_friendly_errors'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/bin/bundle:20:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/bin/bundle:23:in `load'
        from /home/vagrant/.rbenv/versions/2.0.0-p353/bin/bundle:23:in `<main>'
```

Trying to convert the component via browser I get:

``` json
{"status":500,"message":"Our administrator has been notified about this event."}
```

**Comment by sheerun** [comment]
@brennovich It's because jquery-ujs has no versions defined (tags on github). We don't compile components with no versions defined. Could you open an issue on jquery-ujs?

I guess message should be more explicit.

**Comment by sheerun** [comment]
btw. from now on you get:

```
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from http://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/..
Fetching gem metadata from http://rails-assets.org/..
Resolving dependencies...
Could not find gem 'rails-assets-jquery-ujs (>= 0) ruby' in the gems available on this machine.
```

When running bundler with this dependency.

**Comment by brennovich** [comment]
@sheerun gotcha! I'll open an issue on jquery-ujs, you can close this one.

Thanks ;)
